### ISSUE TITLE
Golang doesn't support positive lookbehind assertion?

### ISSUE THREAD

**Issue by thinkhy** [StefanSchroeder/Golang-Regex-Tutorial#11]
Seems Golang doesn't support positive lookbehind assertion, below code output "No matched!":

       package main
        import (
            "fmt"
            "regexp"
        )
        func main() {
            s := "abcdef"

            if matched, str := regexp.MatchString(`(?<=abc)def`, s); matched {
                fmt.Println("It's matched ", str)
            } else {
                fmt.Println("Nothing matched!")
            }
        }

**Comment by StefanSchroeder** [comment]
That is correct. This is not a bug. Refer to 
https://github.com/google/re2/wiki/Syntax
to check the supported syntax.

**Comment by thinkhy** [comment]
I also notice Russ Cox's statement in (Golang-nuts)[https://groups.google.com/forum/#!topic/golang-nuts/7qgSDWPIh_E] . 
 
```  
The lack of generalized assertions, like the lack of backreferences, 
is not a statement on our part about regular expression style.  It is 
a consequence of not knowing how to implement them efficiently.  If 
you can implement them while preserving the guarantees made by the 
current package regexp, namely that it makes a single scan over the 
input and runs in O(n) time, then I would be happy to review and 
approve that CL.  However, I have pondered how to do this for five 
years, off and on, and gotten nowhere. 
```

**Comment by sergeevabc** [comment]
Oh, fellas, it makes life so harder.
For example, ```(\w+)(\.\w+)+(?!.*(\w+)(\.\w+)+)``` to get a filename from URL does not work.

**Comment by StefanSchroeder** [comment]
When retrieving a filename from a  URL I would use 'split' at '/' and then take the last item. No need for regex.
