### ISSUE TITLE
Cannot validate email using regexp in Chapter 3

### ISSUE THREAD

**Issue by tannineo** [StefanSchroeder/Golang-Regex-Tutorial#17]
I'm writing test cases and trying to validate email:  
`ohno-as.cxeq@foo.comeonbaby.heyhey`  
using the regexp from the cookbook  
```go
regexp.Compile(`(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})`)
```
`false` is expected for there are 6 characters after `.` at the end.  
but the result is `true`  
I fix it using:  
```go
regexp.Compile(`\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3}$`)
``` 
Do I misuse or misunderstand anything?

**Comment by StefanSchroeder** [comment]
Email-addresses are notoriously hard to validate. The example for a regexp that I presented was not meant to be covering all possible valid addresses, but to be a first quick check. If you are interested in  battle-proven approaches I suggest to learn more about the topic by reading the sources of popular frameworks, like Wordpress, Joomla or the like. I would assume that they have solved this problem long ago. Furthermore watch this entertaining presentation: 

https://fosdem.org/2018/schedule/event/email_address_quiz/
